_id: 67f78317f2d5fa229c48a808
title: Service
description: Describe your new bucket
icon: cases
primary: name
readOnly: false
history: false
properties:
  name:
    type: string
    title: name
    description: Description of the name input
    options:
      position: bottom
  duration:
    type: number
    title: duration
    description: "Unit: minutes"
    options:
      position: bottom
    minimum: 0
  price:
    type: number
    title: price
    description: "Unit: $"
    options:
      position: bottom
    minimum: 0
acl:
  write: true==true
  read: true==true
order: 3
