_id: 67f78347ec97c82316ab19c3
title: Branch
description: Describe your new bucket
icon: apartment
primary: name
readOnly: false
history: false
properties:
  name:
    type: string
    title: name
    description: Description of the name input
    options:
      position: bottom
  address:
    type: textarea
    title: address
    description: Description of the address input
    options:
      position: bottom
  working_hours:
    type: array
    title: working_hours
    description: Description of the working_hours input
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        day_of_week:
          type: number
          title: day_of_week
          description: Description of the day_of_week input
          options:
            position: bottom
          enum:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
        hours:
          type: array
          title: hours
          description: Description of the hours input
          options:
            position: bottom
          items:
            title: Title of the items
            type: object
            properties:
              from:
                type: string
                title: from
                description: Description of the from input
                options:
                  position: bottom
                pattern: ^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$
              until:
                type: string
                title: until
                description: Description of the until input
                options:
                  position: bottom
                pattern: ^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$
  employees:
    type: relation
    title: employees
    description: Description of the employees input
    options:
      position: bottom
    relationType: onetomany
    dependent: false
    bucket:
      resourceFieldRef:
        schemaName: spica-appointment-asset-employee-bucket
acl:
  write: true==true
  read: true==true
order: 5
