_id: 67f78363704feb2340c4837f
title: Public Holiday
description: Describe your new bucket
icon: domain_disabled
primary: name
readOnly: false
history: false
properties:
  name:
    type: string
    title: name
    description: Description of the name input
    options:
      position: bottom
  from:
    type: date
    title: from
    description: Description of the from input
    options:
      position: bottom
  until:
    type: date
    title: until
    description: Description of the until input
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 6
